In [2]:
!pip install plotly pandas

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [5]:
url = "https://raw.githubusercontent.com/datasets/population/master/data/population.csv"
df = pd.read_csv(url)

df.head()

  Country Name Country Code  Year  Value
0        Aruba          ABW  1960  54922
1        Aruba          ABW  1961  55578
2        Aruba          ABW  1962  56320
3        Aruba          ABW  1963  57002
4        Aruba          ABW  1964  57619

In [6]:
df = df.dropna()

df.columns = ["Country", "Code", "Year", "Population"]

df.head()

  Country Code  Year  Population
0   Aruba  ABW  1960       54922
1   Aruba  ABW  1961       55578
2   Aruba  ABW  1962       56320
3   Aruba  ABW  1963       57002
4   Aruba  ABW  1964       57619

In [7]:
pakistan_data = df[df["Country"] == "Pakistan"]

line_fig = px.line(pakistan_data,
                   x="Year",
                   y="Population",
                   title="Population Growth of Pakistan")

line_fig.show()

In [8]:
latest_year = df["Year"].max()

top10 = df[df["Year"] == latest_year] \
        .sort_values(by="Population", ascending=False) \
        .head(10)

bar_fig = px.bar(top10,
                 x="Country",
                 y="Population",
                 title="Top 10 Countries by Population")

bar_fig.show()

In [9]:
scatter_data = df[df["Year"] == 2020]

scatter_fig = px.scatter(scatter_data,
                         x="Population",
                         y="Year",
                         size="Population",
                         hover_name="Country",
                         title="Scatter Plot with Hover")

scatter_fig.show()

In [10]:
map_data = df[df["Year"] == 2020]

map_fig = px.choropleth(map_data,
                        locations="Code",
                        color="Population",
                        hover_name="Country",
                        title="World Population Map")

map_fig.show()

In [12]:
sample = df[df["Year"] == 2020].head(50)

fig3d = px.scatter_3d(sample,
                      x="Population",
                      y="Year",
                      z="Population",
                      color="Country",
                      title="3D Scatter Plot")

fig3d.show()

In [13]:
anim_fig = px.scatter(df,
                      x="Population",
                      y="Country",
                      size="Population",
                      animation_frame="Year",
                      title="Population Over Time Animation")

anim_fig.show()

In [15]:
dashboard = make_subplots(
    rows=2, cols=2,
    subplot_titles=("Line Chart", "Bar Chart", "Scatter Plot", "Map"),
    specs=[[{"type": "xy"}, {"type": "xy"}],
           [{"type": "xy"}, {"type": "choropleth"}]]
)

# Line chart
for trace in line_fig.data:
    dashboard.add_trace(trace, row=1, col=1)

# Bar chart
for trace in bar_fig.data:
    dashboard.add_trace(trace, row=1, col=2)

# Scatter plot
for trace in scatter_fig.data:
    dashboard.add_trace(trace, row=2, col=1)

# Map (special handling)
for trace in map_fig.data:
    dashboard.add_trace(trace, row=2, col=2)

dashboard.update_layout(
    height=800,
    title_text="Global Population Dashboard"
)

dashboard.show()

In [16]:
dashboard.write_html("dashboard.html")

print("✅ File saved as dashboard.html")

✅ File saved as dashboard.html